name: stamp-figures
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - ipykernel
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - matplotlib
  - seaborn
  - anndata
  - scanpy
  - umap-learn
  - leidenalg
  - python-igraph
  - pytorch>=2.1
  - tqdm
  - pyyaml
  - r-base>=4.2
  - r-qs
  - bioconductor-singlecellexperiment
  - pip:
      - scvi-tools>=1.1,<1.2
